#creating data/basic_cmds.o from data/basic_cmds.s. We are doing this to ultimately create a simple binary that is just for exploring.
#sks
data/basic_cmds.o: data/basic_cmds.s
	as -g data/basic_cmds.s -o data/basic_cmds.o
#creating simpleone_cmds.o
data/simpleone_cmds.o: data/simpleone_cmds.s
	as -g data/simpleone_cmds.s -o data/simpleone_cmds.o

#creating dummy.o from dummy.s
dummy.o: dummy.s
	as -g dummy.s -o dummy.o

#building dummy exacutable linked with data/basic_cmds.o
dummy: dummy.o data/basic_cmds.o
	ld -g dummy.o data/basic_cmds.o -o dummy

#creating calc.o from calc.s
calc.o: calc.s
	as -g  calc.s -o calc.o
#creating and.o from and.s
and.o: and.s
	as -g and.s -o and.o
#creating or.o from or.s
or.o: or.s
	as -g or.s -o or.o
#creating sum.o from sum.s
sum.o: sum.s
	as -g sum.s -o sum.o

upper.o: upper.s
	as -g upper.s -o upper.o

#building calc_basic and linking it to data/basic_cmds.o, and.o, sum.o, or.o
calc_basic: calc.o data/basic_cmds.o and.o sum.o or.o upper.o
	ld -g and.o calc.o or.o sum.o upper.o data/basic_cmds.o -o calc_basic


calc_simpleone: calc.o data/simpleone_cmds.o and.o sum.o or.o upper.o
	ld -g and.o calc.o or.o sum.o upper.o data/simpleone_cmds.o -o calc_simpleone

calc_simplerandom: calc.o data/simplerandom_cmds.o and.o sum.o or.o upper.o
	ld -g and.o calc.o or.o sum.o upper.o data/simplerandom_cmds.o -o \
calc_simplerandom

calc_basicwithupper: data/basicwithupper_cmds.o calc.o and.o sum.o or.o upper.o
	ld -g and.o upper.o calc.o or.o sum.o data/basicwithupper_cmds.o -o calc_basicwithupper

calc_upperonly: data/upperonly_cmds.o calc.o and.o sum.o or.o upper.o
	ld -g and.o upper.o calc.o or.o sum.o data/upperonly_cmds.o -o calc_upperonly


calc_easy: data/easy_cmds.o calc.o and.o sum.o or.o upper.o
	ld -g and.o upper.o calc.o or.o sum.o data/easy_cmds.o -o \
calc_easy


arraysum.o: arraysum.s
	as -g arraysum.s -o arraysum.o 

data/arraysum_cmds.o: data/arraysum_cmds.s
	as -g data/arraysum_cmds.s -o data/arraysum_cmds.o

calc_arraysum: data/arraysum_cmds.o arraysum.o calc.o and.o or.o sum.o upper.o
	ld -g arraysum.o data/arraysum_cmds.o calc.o and.o or.o sum.o upper.o -o calc_arraysum
